### ISSUE TITLE
Make `subspace provision` command

### ISSUE THREAD

**Issue by boatrite** [tenforwardconsulting/subspace#10]
The idea is that subspace will work more like git or cap, having multiple commands to use with the `subspace` executable. One of these should be provision. e.g. `subspace dev provision`, `subspace production provision` (same order as `cap`).

Part of this should be getting rid of the separate playbooks for the environments (since they should be the same anyways). We should have one `provision.yml` playbook that takes the hosts to run on from the subspace command.

We could even have `subspace dev,production provision` be a valid command. There's no technical reason that couldn't work.

**Comment by samsonasu** [comment]
I did this, it's `subspace provision dev`
