### ISSUE TITLE
AWS Ubuntu 16.04 Instances don't have `python` or `aptitude` installed

### ISSUE THREAD

**Issue by petitJAM** [tenforwardconsulting/subspace#41]
I ran into a problem with provisioning stimmi and had to ssh in and manually install python and aptitude

https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f

This is for `python`, but can probably easily work for `aptitude` as well

**Comment by boatrite** [comment]
Fixed
