### ISSUE TITLE
authorized_keys should append instead of replace

### ISSUE THREAD

**Issue by samsonasu** [tenforwardconsulting/subspace#84]
and arguably it should only be for the deploy user.  I think the latter, but at worst it should not overwrite the main ubuntu user's authorized key since it's possible to lock out the user who initially runs provision if their key isn't in the authorized_keys file

**Comment by boatrite** [comment]
I think replace is fine. We need a way to get rid of keys and having to ssh seems annoying. I think just not doing it for the ubuntu user at all would be sufficient.

**Comment by samsonasu** [comment]
replace is fine for deploy, and i think we're in agreement that ubuntu should use the key from AWS and not our slew of personal ones, yes?

**Comment by boatrite** [comment]
yeah i agree with that.

**Comment by samsonasu** [comment]
shipped in 0.4.14
